### ISSUE TITLE
The environment variable 'NODE_ICU_DATA' is not processed correctly 

### ISSUE THREAD

**Issue by luochen1990** [unicode-org/full-icu-npm#12]
* **Version**: v7.9.0
* **Platform**: Windows 10 (64-bit)
* **Subsystem**: none

When `console.log(require("full-icu").datPath())`, the environment variable 'NODE_ICU_DATA' seems not considered.

**Comment by srl295** [comment]
@luochen1990 this function gives the data path of the `full-icu` installed data.  It doesn't know the data path that Node uses.

**Comment by srl295** [comment]
closing this, please reopen if needed.
