### ISSUE TITLE
Postinstall message seems outdated

### ISSUE THREAD

**Issue by vsemozhetbyt** [unicode-org/full-icu-npm#16]
> By the way, if you have full data, running this in node:
> \> new Intl.DateTimeFormat('es',{month:'long'}).format(new Date(9E8));
> ... will show “enero”. If it shows “January” you don't have full data.

In last Node.js versions with `small-icu`, this code returns `'M01'`. See also the example in the https://nodejs.org/api/intl.html#intl_embed_a_limited_set_of_icu_data_small_icu

**Comment by srl295** [comment]
@vsemozhetbyt hm—thanks. will investigate.

**Comment by srl295** [comment]
@vsemozhetbyt I think this  was a bug, now fixed.
