### ISSUE TITLE
Anyway to print the icu data download url directly?

### ISSUE THREAD

**Issue by luochen1990** [unicode-org/full-icu-npm#19]
Is there some way to just print the  icu data download url directly?
Since download & copy automaticly cause authority problems sometime. And it is headachy if there is no way to do these manually.

**Comment by srl295** [comment]
@luochen1990 what kind of authority problems? Anyway you can download from NPM.  This package doesn't fetch a specific URL, but it prints out the version of https://www.npmjs.com/package/icu4c-data

in fact, just see: 

```
node -e 'console.dir("npm install icu4c-data@"+process.config.variables.icu_ver_major+process.config.variables.icu_endianness)'
```

**Comment by luochen1990** [comment]
The authority problem occurs when I download and extract node directly without using a package manager to install it.  I believe it is not caused by this package, so never mind.

**Comment by luochen1990** [comment]
Thx, this command seems useful. And I will use the following one for short:
```
node -p "'npm install icu4c-data@'+process.config.variables.icu_ver_major+process.config.variables.icu_endianness"
```

**Comment by srl295** [comment]
> The authority problem occurs when I download and extract node directly without using a package manager to install it. I believe it is not caused by this package, so never mind.

OK, may I ask why you are doing it?

> Thx, this command seems useful. And I will use the following one for short:
> node -p "'npm install icu4c-data@'+process.config.variables.icu_ver_major+process.config.variables.icu_endianness"

I don't think it's a good idea in general.  I'd like to hear why the `full-icu` package can't work… that's what it is designed to do.

I'd like to make changes in how data loading works, so the above command will break.
