### ISSUE TITLE
Broken on Node.js 9.x

### ISSUE THREAD

**Issue by MylesBorins** [unicode-org/full-icu-npm#20]
When running npm install we receive the following error

> 
> full-icu@1.2.1-0 postinstall /Users/mborins/code/full-icu-npm
> node postinstall.js
>
> npm install icu4c-data@60l (Node 9.2.0 and small-icu 60.1) -> icudt60l.dat
full-icu$ /Users/mborins/.nvm/versions/node/v9.2.0/bin/node /Users/mborins/.nvm/versions/node/v9.2.0/lib/node_modules/npm/bin/npm-cli.js install icu4c-data@60l
npm ERR! code ETARGET
npm ERR! notarget No matching version found for icu4c-data@60l
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
>
> npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mborins/.npm/_logs/2017-12-04T20_48_48_472Z-debug.log
/Users/mborins/code/full-icu-npm/install-spawn.js:41
		throw(Error(cmdPath + ' ' + args.join(' ') + ' --> status ' + spawned.status));

It would appear icu4c-data@60l is not published

We are going to have to skip full-icu-test in CITGM until this is resolved

**Comment by refack** [comment]
Refs: http://bugs.icu-project.org/trac/ticket/11617#comment:7

**Comment by srl295** [comment]
@refack thanks… the GH issue is sufficient.  Anwyay,should be fixed now, please retest

**Comment by srl295** [comment]
works for me, reopen if not…
