### ISSUE TITLE
It gives space as thousand seperator instead of . for German Locale

### ISSUE THREAD

**Issue by Sutikshan** [unicode-org/full-icu-npm#21]
Hi,
I am not sure when using full-icu, why Intl.NumberFormat.format() formats the number with 'white-space' as thousand separator and not . as used in de-AT locale.
I wrote following test file :-

```
const fullIcu = require('full-icu');

const numberFormat = new Intl.NumberFormat('de-AT', {
  minimumFractionDigits: 2,
  maximumFractionDigits: 5,
});
console.log(numberFormat.format(1234.52));
console.dir(fullIcu);
```
and run it via :-
`node --icu-data-dir=./node_modules/full-icu ./numtest.js`

It gives me following output

```
1 234,52 //note space instead of .
{ nodever: '9.3.0',
  node_maj: '9',
  node_min: '3',
  icu_small: true,
  icuver: '60.1',
  icumaj: '60',
  icuend: 'l',
  icupkg: 'icu4c-data@60l',
  icudat: 'icudt60l.dat',
  haveDat: [Function: haveDat],
  datPath: [Function: datPath] }
```

**Comment by Sutikshan** [comment]
I think, it is giving me thin-space as thousand separator as mentioned on wiki - https://en.wikipedia.org/wiki/Decimal_mark
But browser do agree to give me , as thousand separator for german locales. Any guideline to make full-icu give me , as thousand separator.

**Comment by srl295** [comment]
By the way, there's no reason to `require('full-icu')` that has no effect on internationalization. It's the `npm install full-icu` and launching node with the right option which has an effect.

**Comment by srl295** [comment]
For what it's worth, I see `1 234,52` in Chrome and Firefox but not Safari. The thousands separator of ` ` is correct per CLDR data https://www.unicode.org/cldr/charts/latest/by_type/numbers.symbols.html#a1ef41eaeb6982d ( see under de_AT)

**Comment by srl295** [comment]
Closing this, it is more of a CLDR or ICU issue.
