### ISSUE TITLE
full-icu-npm 1.2.1 not compatible with node 10

### ISSUE THREAD

**Issue by fono** [unicode-org/full-icu-npm#25]
We would like to use node 10 in our project and full-icu is required for it. The current full-icu-npm v1.2.1 works great with node 8, but with v10 it says `could not initialize ICU (check NODE_ICU_DATA or --icu-data-dir parameters)`. I know node 10 is not in LTS phase yet, but according to the [node.js release schedule](https://github.com/nodejs/Release#release-schedule), it will be LTS when our project goes live, and it would be awesome to use node 10 with full-icu-npm by then.

**Comment by srl295** [comment]
@fono need some more details. Can you give the output of `node -p process.versions.icu` ? If it's 62.1 it's probably that 62.1 data was not published  (it is published now).    I don't think there's an incompatiblity with node 10 per se.

**Comment by srl295** [comment]
@fono did you re-run `npm install full-icu` after upgrading to 10?  Because probably what you installed was something older than 61.1.   `npm install full-icu` has to be re-run every single time the node version changes (or the hardware switches to little/big endian)

**Comment by fono** [comment]
@srl295 Thanks, that was the missing piece. I thought `npm update` whould be enough. Reinstalling the module did the trick.
