### ISSUE TITLE
Returns incorrect date for locale da-dk

### ISSUE THREAD

**Issue by lohfu** [unicode-org/full-icu-npm#32]
To get localization in a docker container i installed the `full-icu` package. However, the output of a date.toLocaleString call in my container for the locale da-dk differs from my locally installed nodejs and chromium browser.

The line
```
date.toLocaleString('da-dk', { year: 'numeric', month: 'numeric', day: 'numeric' });
```
returns dates like 1.1.2019 in my locally installed node 11.12 (from the official arch linux repos) and chromium browser but 1/1/2019 in the container running node 10.15 with full-icu installed.

**Comment by srl295** [comment]
@lohfu sorry for the late response. You have to not only install full-icu but also set the `--icu-data-dir` command line option or environment variable as directed when you install.

Closing, please reopen if needed.

**Comment by lohfu** [comment]
@srl295 i have set the --icu-data-dir, the other locales i tested work consistently across browser versions.

however, i realised that maybe the da-dk locale has been updated between ICU 62 and 63... could this be the case?
