### ISSUE TITLE
postinstall.js does not exit

### ISSUE THREAD

**Issue by Huulivoide** [unicode-org/full-icu-npm#33]
postinstall.js file begins by checking for known "will not work" conditions and printing an error message on the console all which end in 'Exiting.'  But the script does not exit. Instead it keeps on going until it fails.

My case:
Archlinux upgraded the system ICU to version 64.
Node on Arch is compiled with system-icu → postinstall notices node is using system icu, but still continues on and tries to install icu4c-data@64l resulting in failure to install the package.

**Comment by eagleflo** [comment]
I also encountered this on Arch Linux with Node v11.14.

**Comment by srl295** [comment]
fixed in #34 via a632e50ae10ce25152830d296b06256cf81449a1
