### ISSUE TITLE
Issue with full-icu

### ISSUE THREAD

**Issue by WestArjan** [unicode-org/full-icu-npm#45]
![image](https://user-images.githubusercontent.com/29145465/76856347-5e300100-6853-11ea-95a4-26c444fbf269.png)

I have tried all the other fixes suggested ( npm rebuild, npm install full-icu --force, deleting it and rebuilding ).

Any suggestions on how to further troubleshoot this I would appreciate.

**Comment by JakeAve** [comment]
I've seen that before, I don't know everything about your situation but adding a `.` to the beginning of the path fixed it for me, which doesn't make a ton of sense. So `cross-env NODE_ICU_DATA=/node_modules/full-icu` didn't work, but `cross-env NODE_ICU_DATA=./node_modules/full-icu` did work. The same went for adding the `--icu-data-dir` flag. I had to add a `.` before the path.

**Comment by srl295** [comment]
@WestArjan Please give your full environment.  If 'cross' means cross compliling, it's possible that the full-icu detected the wrong environment or ICU version.

**Comment by WestArjan** [comment]
I kept getting this issue trying to run a node client on a linux distro called openSUSE. I couldn't replicate it on windows nor ubuntu and after a while looking how I could fix this issue I changed my distro fedora and it works fine now.

My geuss is it somehow openSUSE related. I can't really help troubleshoot any further since the openSUSE boot has been formatted.

**Comment by srl295** [comment]
@WestArjan we probably need the command line you used to invoke this.I'll close this unless there's more detail.
