### ISSUE TITLE
Post-Install Failure on node 12.16.2

### ISSUE THREAD

**Issue by Snugug** [unicode-org/full-icu-npm#46]
On Node 12.16.2/npm 6.14.4, when installing this module, the following error is thrown during post-install. I believe it's because the module is trying to find `icu4c-data@651` but the module ships with `icu4c-data@641`. I'm unsure why this patch Node bump/minor NPM bump causes this breakage, but installation _does not_ fail on 12.16.1/6.13.4.

```
Error: /opt/hostedtoolcache/node/12.16.2/x64/bin/node /opt/hostedtoolcache/node/12.16.2/x64/lib/node_modules/npm/bin/npm-cli.js install icu4c-data@65l --> status 1
    at npmInstallNpm (/home/runner/work/project/project/node_modules/full-icu/install-spawn.js:62:9)
    at Object.<anonymous> (/home/runner/work/project/project/node_modules/full-icu/postinstall.js:72:2)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
npm ERR! code ELIFECYCLE
```

**Comment by A** [comment]
Also fixed this issue, by temporary downgrade node to `12.16.1`

**Comment by zgriesinger** [comment]
We also hit this issue almost instantly after 12.16.2 was released in our CI that was running against Node 12.x and Docker builds using `node12-slim`.

Had to downgrade to 12.16.1 to fix our builds and get everything going again

**Comment by jacekk** [comment]
Quite a change in Node --> https://github.com/nodejs/node/pull/30232/files . Anyone knows Captain America to save us? ;)

**Comment by srl295** [comment]
ok, I see.

**Comment by srl295** [comment]
Now uploading 65...

**Comment by srl295** [comment]
> I'm unsure why this patch Node bump/minor NPM bump causes this breakage, but installation does not fail on 12.16.1/6.13.4.


because i didn't upload the 65 binaries yet

**Comment by srl295** [comment]
people, NPM is timing out trying to do the upload.

**Comment by srl295** [comment]
```
$ docker run --rm -it node:12-slim npm i full-icu

> full-icu@1.3.1 postinstall /node_modules/full-icu
> node postinstall.js

npm install icu4c-data@65l (Node 12.16.2 and small-icu 65.1) -> icudt65l.dat
full-icu$ /usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js install icu4c-data@65l
npm notice created a lockfile as package-lock.json. You should commit this file.
+ icu4c-data@0.65.2
added 1 package from 1 contributor and audited 1 package in 6.931s
found 0 vulnerabilities

 √ icudt65l.dat (link)
```

**Comment by srl295** [comment]
65b also uploaded

**Comment by srl295** [comment]
66b uplaoded, hopefully 66l soon

**Comment by zgriesinger** [comment]
@srl295 Thanks for the fix! Can confirm this resolved our issue 🎉

**Comment by jacekk** [comment]
@srl295 Same here. Thx

**Comment by MylesBorins** [comment]
Hey All, from node team here. Sorry about not updating sooner. Will give y'all a heads up here next time

**Comment by srl295** [comment]
> Hey All, from node team here. Sorry about not updating sooner. Will give y'all a heads up here next time

Good incentive to get #36 done… makes this issue go away!
