### ISSUE TITLE
dynamically updating full-icu

### ISSUE THREAD

**Issue by bcoe** [unicode-org/full-icu-npm#51]
👋 I'm helping a user in a dynamic runtime environment, where their process is sometimes restarted on a newer Node.js verison, e.g., `v12.1.0 -> v12.2.0`, without a full deploy of the service.

This has been causing issues with `full-icu`, as ICU expects a data file paired to the Node.js version.

I was thinking of giving the advice of running a script like this:

```bash
#!/usr/bin/env bash

mkdir -p /tmp/icu/node_modules
cd /tmp/icu
VERSION=$(node -e 'console.info("icu4c-data@"+process.config.variables.icu_ver_major+process.config.variables.icu_endianness)')
npm i $VERSION
```

As a `prestart` script in their npm module, such that, in these situations where Node has been updated underneath them, they end up with a working version of `icu4c-data`.... my concern. was that this would lead to slower cold start times.

I was wondering if you have any advice, have seen similar approaches, or know of libraries that would do some of this work for the user?

**Comment by srl295** [comment]
Hm.  Maybe instead of invoking node, just take a quick checksum on `which node` or something?  then you could have an empty `.ok/1234abcd` file as a marker that you've run `npm i full-icu` for that version?

**Comment by bcoe** [comment]
@srl295 thanks for the follow up. Ultimately, we decided that rather than directing the customer to dynamically update full-icu, we'd ship Node.js with full ICU support. We're in a healthy place now 😄

**Comment by srl295** [comment]
🎉 
Everyone wins.  Even those being paid for bandwidth and disk space:)
