### ISSUE TITLE
Postinstall failes in CI with no public internet and only a private registry

### ISSUE THREAD

**Issue by morbidick** [unicode-org/full-icu-npm#52]
Hi,
thank you for this nice package to easily install the needed ICU data. 

Locally on the development machine it works like a charm. But in CI we have no internet and only a custom registry (which mirrors on demand the npm one).
To support that we set the registry key in .npmrc but it doesn't seem to respect it and still calls the yarn registry.

Maybe an issue with the location of our yarn.js?
Attached is part of the failing log, I would appreciate if you had some hints :)

```
17:21:08  error /workspace/node_modules/full-icu: Command failed.
17:21:08  Exit code: 1
17:21:08  Command: node postinstall.js
17:21:08  Arguments: 
17:21:08  Directory: workspacenode_modules/full-icu
17:21:08  Output:
17:21:08  npm install icu4c-data@62l (Node 10.15.3 and small-icu 62.1) -> icudt62l.dat
17:21:08  Looks like you are using yarn���
17:21:08  full-icu$ /jenkins_share/tools/node-v10.15.3-linux-x64/bin/node /jenkins_share/tools/node-v10.15.3-linux-x64/lib/node_modules/yarn/bin/yarn.js add icu4c-data@62l --no-lockfile --ignore-scripts
17:21:08  yarn add v1.17.3
17:21:08  info No lockfile found.
17:21:08  [1/4] Resolving packages...
17:21:08  error An unexpected error occurred: "https://registry.yarnpkg.com/icu4c-data: connect ECONNREFUSED 104.16.17.35:443".
17:21:08  info If you think this is a bug, please open a bug report with the information provided in "/workspace/node_modules/full-icu/yarn-error.log".
17:21:08  info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
17:21:08  /workspace/node_modules/full-icu/install-spawn.js:62
17:21:08  		throw(Error(cmdPath + ' ' + args.join(' ') + ' --> status ' + spawned.status));
```

**Comment by srl295** [comment]
@morbidick this would not work at all if I pull from Github, #36 

Also, as above, the command it is running ends up being:
```shell
yarn add icu4c-data@62l --no-lockfile --ignore-scripts
```
Can you get that to run in the environment? Or some equivalent?

**Comment by morbidick** [comment]
Hi @srl295 thank you for your answer, running it with an explicit version seems to work. I just realized another problem. Our CI runs with node 10 the production image uses node 12, so it would never match :/ I think the easiest fix for us is to use node 14 which bundles full-icu by default.
