### ISSUE TITLE
nl-BE bug in currency formatting

### ISSUE THREAD

**Issue by Timkor** [unicode-org/full-icu-npm#55]
```javascript
let options = {
    style: 'currency',
    currency: 'eur',
};

let value = new Intl.NumberFormat('nl-be', options).format(10);

```

Server side `value` will render to:

> 10,00 €

While client side in Chrome 85 this will render to:

> € 10,00

Node version: 12.8.0
Package version: 1.3.1

**Comment by srl295** [comment]
@Timkor this is not the place to report this— report it against Node.js or further upstream. full-icu is just a loader.
