### ISSUE TITLE
Incomplete yarn regex

### ISSUE THREAD

**Issue by joey-colon** [unicode-org/full-icu-npm#56]
I was unable to install the package when my yarn path (`npm_execpath`) was pointing to a `.cjs` file. Because of the [regex](https://github.com/unicode-org/full-icu-npm/blob/master/install-spawn.js#L14) not capturing `.cjs` file extensions, it would attempt running `npm install` which ended up throwing an error since yarn forces to use `yarn add`.

Resolved by changing my yarn path via .yarnrc to a file with `.js` extension.

edit: looks like #54 will fix 

Stack trace: 

error /Users/corgi/code/project/node_modules/full-icu: Command failed.
Exit code: 1
Command: node postinstall.js
Arguments:
Directory: /Users/corgi/code/project/node_modules/full-icu
Output:
npm install icu4c-data@64l (Node 12.13.0 and small-icu 64.2) -> icudt64l.dat
full-icu$ /Users/corgi/.nvm/versions/node/v12.13.0/bin/node /Users/corgi/code/.yarn/releases/yarn-1.19.1.cjs install icu4c-data@64l
yarn install v1.19.1
info No lockfile found.
error `install` has been replaced with `add` to add new dependencies. Run "yarn add icu4c-data@64l" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
/Users/corgi/code/project/node_modules/full-icu/install-spawn.js:62
		throw(Error(cmdPath + ' ' + args.join(' ') + ' --> status ' + spawned.status));
		^

Error: /Users/corgi/.nvm/versions/node/v12.13.0/bin/node /Users/corgi/code/.yarn/releases/yarn-1.19.1.cjs install icu4c-data@64l --> status 1
    at npmInstallNpm (/Users/corgi/code/project/node_modules/full-icu/install-spawn.js:62:9)
    at Object.<anonymous> (/Users/corgi/code/project/node_modules/full-icu/postinstall.js:72:2)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)

**Comment by srl295** [comment]
@joey-colon fixed in #54 ?

**Comment by joey-colon** [comment]
> @joey-colon fixed in #54 ?

yup looks good!

**Comment by srl295** [comment]
Fixed.

**Comment by joey-colon** [comment]
> Fixed.

could you also publish a new tag for this fix?

**Comment by srl295** [comment]
Yep

**Comment by srl295** [comment]
released as v1.3.3 https://www.npmjs.com/package/full-icu

**Comment by srl295** [comment]
Fixed in 06c60851656cce16e8223e6e6c392e52a11d40ec
